### ISSUE TITLE
Reboot to Recovery Issues in TWRP v3.1.0-0 D2VZW 

### ISSUE THREAD

**Issue by Ibuprophen** [TeamWin/android_device_samsung_d2vzw#1]
The feature for Reboot to Recovery in TWRP now only Reboots the Device and not back into Recovery. 

I confirmed twice that this issue was not present in the v3.0.2-0.

In order for me to Reboot back into Recovery, i have to immediately hold the button combinations to re-enter Recovery. 

The issue is pretty self explanatory. 

Thank You!

**Comment by timschumi** [comment]
Did TWRP recognize a working OS when you rebooted?
If not (which means that you had the "No OS installed, are you sure you want to reboot" screen), it should probably be fixed with 3.1.1 (more exactly this commit here: https://gerrit.omnirom.org/#/c/22509/)

EDIT: I just saw that the d2vzw 3.1.1 build failed (https://jenkins.twrp.me/job/d2vzw-prod/9/consoleText). You should probably mail bigbiff about this so he can fix the error and make a rebuild (I'm not sure how this error can be resolved apart from creating the file manually, because it's caused by a prebuilt kernel. Suprisingly, other devices which use a prebuilt kernel do not seem to have this problem)

**Comment by Ibuprophen** [comment]
I didn't/don't receive any errors regarding this issue.... 

If I'm in the main screen of TWRP and select Reboot then Recovery, it reboots the device without entering back into recovery. 

That's about the gist of it. 

I used the example situation on the first one as more of an example because that is when i had first noticed the issue. I apologize for not making this clearer. 

To this day, since the TWRP update to v3.1.0-0, if I'm in TWRP and attempt to reboot to recovery, it will just reboot the device without automatically entering the recovery. 

In addition, this issue was not present and worked in TWRP v3.0.2-0. 

Thank You!

**Comment by timschumi** [comment]
With error I meant the build error which prevents that your device gets TWRP 3.1.1-0, which includes a few bugfixes.
I don't know any other things that could cause this issue, you probably better ask your maintainer.

**Comment by Ibuprophen** [comment]
I sent this issue via email, PM's, posted in Github and XDA... 

Issue ultimately ignored by TeamWin... 

Closed.
